### ISSUE TITLE
Allow to customize line parsing

### ISSUE THREAD

**Issue by climba03003** [pinojs/pino-abstract-transport#21]
It is not always good to parse the line before passing it to another stream or transport. For example `mongodb` do not allow the below data format insert to database.

1. dot in property
```json
{
  "foo.bar": "baz"
}
```
2. dollar sign in property
```json
{
  "$foo": "bar"
}
```

I can see that most of the plugin is moving toward using `pino-abstract-transport` as a base constructor. It is better to allow custom parsing to meet different needs of database format.

Related https://github.com/pinojs/pino-mongodb/pull/63

**Comment by mcollina** [comment]
If we skipped parsing... how would it help pino-mongodb for example?

cc @Eomm

**Comment by climba03003** [comment]
> 
> 
> If we skipped parsing... how would it help pino-mongodb for example?
> 
> cc @Eomm

From what I imagine, the usage would be

```js
'use strict'

const build = require('pino-abstract-transport')

module.exports = function (opts) {
  return build(function (source) {
    source.on('data', function (obj) {
      console.log(obj)
    })
  }, {
    parseLine: function(line) {
      // do something about the line from string
      // e.g. replace . to _
      line = line.replace(/\./g, '_')
      return JSON.parse(line)
    }
  })
}
```

We can also pass https://github.com/Eomm/pino-mongodb/blob/pino-7/lib/log.js this file directly to the option and we do not need a optional check for `line` input.

More advance usage is all the pino transport pass a `parseLine` option directly from user to `pino-abstract-transport` and each transport only provide a safe and simple parsing function.

Example
```js
'use strict'

const build = require('pino-abstract-transport')
function defaultParser = JSON.parse

module.exports = function (opts) {
  const parseLine = typeof opts.parseLine === 'function' ? opts.parseLine : defaultParser
  return build(function (source) {
    source.on('data', function (obj) {
      console.log(obj)
    })
  }, {
    parseLine
  })
}
```

**Comment by Eomm** [comment]
It is fair to provide a parsing option while keeping the default one as-is

regarding pino-mongodb instead, I would add the note on docs
At this time I tested that the error is swallowed, I will update the PR
