### ISSUE TITLE
TypeScript: `build` is not callable

### ISSUE THREAD

**Issue by edgarlepe** [pinojs/pino-abstract-transport#71]
## Description of issue

When trying to use the example given in the [pino docs](https://getpino.io/#/docs/transports?id=writing-a-transport):

```typescript
import build from "pino-abstract-transport";
import { SonicBoom } from "sonic-boom";
import { once } from "events";

export default async (options) => {
  const destination = new SonicBoom({
    dest: options.destination || 1,
    sync: false,
  });
  await once(destination, "ready");

  return build(
    async (source) => {
      for await (const { message } of source) {
        const toDrain = !destination.write(message.toUpperCase() + "\n");

        if (toDrain) {
          await once(destination, "drain");
        }
      }
    },
    {
      close: async (err) => {
        destination.end();
        await once(destination, "finish");
      },
    }
  );
};
```

I get the following error for the default `build` export:

```
This expression is not callable.
  Type 'typeof import("PATH_TO_MY_PROJECT/node_modules/pino-abstract-transport/index")' has no call signatures.ts(2349)
```

## Relevant Setup Details

**package.json**
```
{
  ...
  "dependencies": {
    ...
    "pino-abstract-transport": "^1.0.0",
    ...
  }
  ...
}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "esModuleInterop": true
  }
}
```

## Workarounds

I found two workarounds. First, use `build.default` instead of `build` when calling.  The second workaround is to change

https://github.com/pinojs/pino-abstract-transport/blob/87a47cb974dbdbdf1d485687c5f756382e7e6345/index.d.ts#L89

to

```typescript
export = build;
```

---

Could this be an issue with my setup? If this issue is not expected behavior, I can create PR with my latter workaround.

### EDIT

Workaround two does not work.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by FabianFrank** [comment]
The following details might be helpful for anyone running into this or trying to reproduce this.

1. The issue reproduces only if you set
```"module": "node16",
"moduleResolution": "node16"```
in your tsconfig. In the older (and still more commonly used) `node` moduleResolution mode everything works.

2. Once using node16, the types and what is exported by index.js no longer match. Typescript interprets `export default build` as an export named "default", not as _the default export_. Thus the error when trying to do
```
import build from "pino-abstract-transport"

build(...) // allegedly not callable
build.default(...) // allegedly callable but in fact undefined at runtime
```

So the workaround using the current types in a "pure ESM" typescript project is actually
```
import buildOops from "pino-abstract-transport"

const build = buildOops as unknown as typeof buildOops.default
```
